name: Deployment

on:
  push:
    branches: [main] # only push events on source branch trigger deployment

jobs:
  # markdown-images-replace:

  hexo-deployment:
    # needs: markdown-images-replace
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i hexo-theme-nexmoe
        npm i --save hexo-wordcount
        hexo clean
        hexo g

    - name: Hexo Deploy Action
      uses: renzhaosy/hexo-deploy-action@0.0.1
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY: zrtty1998/zrtty1998.github.io.git # The repository the action should deploy to.
        BRANCH: main  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.